### ISSUE TITLE
Incorrect and misleading documentation or bug in defining the provider

### ISSUE THREAD

**Issue by dushevadnqka** [site24x7/terraform-provider-site24x7#105]
Hi team,
I tried to configure the terraform provider as following the documentation (https://registry.terraform.io/providers/site24x7/site24x7/latest/docs). In my case I used only Client ID, Client Secret (required) and Refresh Token (as there is mentioned that it's required to use at least one of Oauth Access or Refresh Token. 
With that configuration the provider didn't work - the error I received on terraform apply (only) was:
```
Error: POST /[resource]: giving up after 5 attempts due to: Post "/[resource]": oauth2: server response missing access_token.
```
The next try was as adding some dummy string as access token, the result was even more weird:
```
Error: POST /[resource]: giving up after 5 attempts due to: Post "/[resource]": unsupported protocol scheme ""
```
How the work got fixed: I simply added and defined the `data_center` attribute to the provider, which was pointed as "Optional" as well and the configuration got work.
Summary:
Probably the documentation is inconsistent with the actual functionality or there is some bug/unexpected behaviour of the provider, but the minimal set which was working for me was:
- Client ID
- Client Secret
- Oauth Refresh Token
- Data Center

Cheers,
Georgi

**Comment by jim-billy-zoho** [comment]
@dushevadnqka Thanks for raising this issue. Have made the "data_center" attribute mandatory in the latest release 1.0.27 - https://registry.terraform.io/providers/site24x7/site24x7/latest/docs
