### ISSUE TITLE
unable to use maintenance_type

### ISSUE THREAD

**Issue by jc-streamsets** [site24x7/terraform-provider-site24x7#112]
is this section of code supposed to be uncommented?

https://github.com/site24x7/terraform-provider-site24x7/blob/eb2cd411396deaec2c8441cb30533776e9fd58cb/site24x7/common/schedule_maintenance.go#L38-L45

I tried to set maintenance_type in resource "site24x7_schedule_maintenance" but it's not recognized:

```
╷
│ Error: Unsupported argument
│
│   on main.tf line 29, in resource "site24x7_schedule_maintenance" "schedule_maintenance_basic":
│   29:   maintenance_type = 3
│
│ An argument named "maintenance_type" is not expected here.
╵
```

**Comment by jim-billy-zoho** [comment]
@jc-streamsets [https://github.com/site24x7/terraform-provider-site24x7/blob/eb2cd411396deaec2c8441cb30533776e9fd58cb/site24x7/common/schedule_maintenance.go#L206](url)

You need not set maintenance_type. The default value is "3" and it is hardcoded. We will uncomment this code when other maintenance types are supported.
