### ISSUE TITLE
site24x7_ssl_monitor and timeout

### ISSUE THREAD

**Issue by azhurbilo** [site24x7/terraform-provider-site24x7#117]
```
 ~ resource "site24x7_ssl_monitor" "xxx" {
      ~ timeout                   = 30 -> 15
    }
  ```
  
  in Terraform we set 15 sec but it's always 30 sec
  
  According API doc I see that `timeout` is required, but from UI there is no such attribute https://www.site24x7.com/help/api/#ssl-certificate
  is it possible that there is problem in API documentation and we don't need to set timeout for SSL monitors?

**Comment by jim-billy-zoho** [comment]
@azhurbilo Thanks for raising the issue. You don't need to set timeout and it is internally handled for the SSL monitor.
