### ISSUE TITLE
site24x7_tag - doesn't support import

### ISSUE THREAD

**Issue by azhurbilo** [site24x7/terraform-provider-site24x7#119]
tried import existed tag by id and Terraform return

`Error: resource site24x7_tag doesn't support import`

it's important feature as you can not create the same tag <name>:<value> by terraform but with other ID, it makes migration to terraform harder

**Comment by JasperPaul** [comment]
Hey there, From where are you trying to import?

**Comment by azhurbilo** [comment]
```
terraform import
              -var ...
              -input=false
              "module.module_name.site24x7_tag.tags['key']" "tag_id"
```

**Comment by jim-billy-zoho** [comment]
@azhurbilo If you want to manage existing tags via terraform, please use the latest version and try importing tags. If you want to just refer existing tag IDs during monitor addition, please use the site24x7_tag data source. Refer the example [here](https://github.com/site24x7/terraform-provider-site24x7/blob/main/examples/tag_us.tf)

**Comment by azhurbilo** [comment]
thank you for super fast reaction! also it will be good to describe it in doc "Import" block https://registry.terraform.io/providers/site24x7/site24x7/latest/docs/resources/tag
