### ISSUE TITLE
enhanced-notification-profiles resource

### ISSUE THREAD

**Issue by azhurbilo** [site24x7/terraform-provider-site24x7#126]
today notice message in site24x7 UI
>  Migrate to the enhanced Notification Profile on or before October 25, 2022. View Preview

could we add support of new "enhanced" notification profiles terraform resource

https://www.site24x7.com/help/api/#enhanced-notification-profiles

**Comment by jim-billy-zoho** [comment]
@azhurbilo Please use our latest version 1.0.34 for managing enhanced notification profiles.
