### ISSUE TITLE
The provider site24x7/site24x7 does not support resource type "site24x7_amazon_monitor".

### ISSUE THREAD

**Issue by rommel-baltazar** [site24x7/terraform-provider-site24x7#128]
Using latest site24x7 provider version 1.0.34 (Also tested with 1.0.33) and getting the following error:

`
│ Error: Invalid resource type
│
│   on aws_monitors.tf line 2, in resource "site24x7_amazon_monitor" "aws_monitor_au_nonprod":
│    2: resource "site24x7_amazon_monitor" "aws_monitor_au_nonprod" {
│
│ The provider site24x7/site24x7 does not support resource type
│ "site24x7_amazon_monitor".
╵
ERRO[0007] 1 error occurred:
        * exit status 1`

**Comment by rommel-baltazar** [comment]
seems was caused by this but the reason why doing so was not explained: https://github.com/site24x7/terraform-provider-site24x7/pull/124

Also, the documentation is not updated here: https://registry.terraform.io/providers/site24x7/site24x7/latest/docs/resources/amazon_monitor

**Comment by jim-billy-zoho** [comment]
@rommel-baltazar We have temporarily disabled amazon monitor addition due to security concerns. We will update here when the issue is fixed.

**Comment by jim-billy-zoho** [comment]
Hi @rommel-baltazar, 

Thank you for your patience. We have supporte Amazon monitor. Please refer - https://registry.terraform.io/providers/site24x7/site24x7/latest/docs/resources/amazon_monitor

Regards,
Jim Billy
