### ISSUE TITLE
Unable to change location profile

### ISSUE THREAD

**Issue by Th0masL** [site24x7/terraform-provider-site24x7#144]
Hello,

It seems like once created, changing the value `location_profile_name` does not change the location profile.

```
  # site24x7_website_monitor.some_monitor["some_site"] will be updated in-place
  ~ resource "site24x7_website_monitor" "some_monitor" {
        id                          = "299771000019XXXXXX"
      + location_profile_name       = "Global NA/EU/AP/SA"
        # (31 unchanged attributes hidden)
    }
```

It's showing changes, but when I look in the UI nothing has changed.

Thanks !

**Comment by jim-billy-zoho** [comment]
@Th0masL Thank you for raising this issue. Issue is fixed in the latest version 1.0.44.
