### ISSUE TITLE
notification_delay_configuration.0.status - Unable to use -1

### ISSUE THREAD

**Issue by anthosz** [site24x7/terraform-provider-site24x7#149]
Hello,

Following the doc (https://registry.terraform.io/providers/site24x7/site24x7/latest/docs/resources/notification_profile), the status of notification_delay_configuration can be -1, 0, 1, 2 or 3.

If I try:
`
  notification_delay_configuration {
    status                 = -1
    business_hours_id      = "-1"
    notification_delay     = 2
    outside_business_hours = "1"
  }
`

I have this error (with and without ""): 
```
│ Error: expected notification_delay_configuration.0.status to be one of [0 2 3], got -1
```

FYI, I use the last version of site24x7 terraform provider.

**Comment by jim-billy-zoho** [comment]
@anthosz Thank you for raising this issue. The "status" attribute in notification_delay_configuration cannot be "-1" as stated in the error. I have updated the documentation accordingly.
