### ISSUE TITLE
Feature Request: DNS Server Monitoring

### ISSUE THREAD

**Issue by vardan-nikoghosyan** [site24x7/terraform-provider-site24x7#150]
Any plan to add DNS Server monitor?

https://www.site24x7.com/help/api/#dns-server

**Comment by jim-billy-zoho** [comment]
@vardan-nikoghosyan Please use the latest version to manage a DNS server monitor. https://registry.terraform.io/providers/site24x7/site24x7/latest/docs/resources/dns_server_monitor
