### ISSUE TITLE
site24x7_monitor_group - health_threshold_count  - unable to set it to 1

### ISSUE THREAD

**Issue by anthosz** [site24x7/terraform-provider-site24x7#151]
Hello,

When we use site24x7_monitor_group.health_threshold_count, we cannot set it to 1 to be able to receive alert group only when all resources are down.

Indeed, when we try to set it to 1, terraform always overwrite it to 0.

It seems to works only for subgroup & not parent group.

Best regards,

**Comment by jim-billy** [comment]
@anthosz Thank you for raising this issue. We have fixed it in the latest version 1.0.45.
