### ISSUE TITLE
Feature request: add location-profile resource support

### ISSUE THREAD

**Issue by azhurbilo** [site24x7/terraform-provider-site24x7#16]
add **location-profile** resource support
https://www.site24x7.com/help/admin/configuration-profiles/location-profile.html

https://www.site24x7.com/help/api/#location-profiles

or if it's hard to implement, add terraform "data-source" support to have ability import id from manually created profile

**Comment by site24x7** [comment]
Location Profile resource supported - 0.0.1-beta.7

Please refer the example - https://github.com/site24x7/terraform-provider-site24x7/blob/main/examples/location_profile_us.tf
