### ISSUE TITLE
Feature request: add tag resource support

### ISSUE THREAD

**Issue by azhurbilo** [site24x7/terraform-provider-site24x7#17]
add **tag** resource support
https://www.site24x7.com/blog/tags-a-smarter-way-to-organize-and-manage-monitors

https://www.site24x7.com/help/api/#tags

**Comment by azhurbilo** [comment]
ideally output of this "tag" resource reuse in monitors https://github.com/site24x7/terraform-provider-site24x7/issues/18

**Comment by azhurbilo** [comment]
@jim-billy as I understand "tag" supported was released 2 days ago right? thnx a lot 👍 
can we close this ticket?

**Comment by site24x7** [comment]
> @jim-billy as I understand "tag" supported was released 2 days ago right? thnx a lot +1 can we close this ticket?

@azhurbilo Thanks for raising issues and following them up.

**Comment by site24x7** [comment]
Tag resource supported - 0.0.1-beta.3
