### ISSUE TITLE
Heartbeat, Monitoring Groups 

### ISSUE THREAD

**Issue by e-bits** [site24x7/terraform-provider-site24x7#170]
Hi, some time ago (#132)  you implemented the Heartbeat monitors.
After different tests we realizised a strange issue.

Threshold-profile type for HEARTBEAT Monitoring is missing. Correct?
There is a little issue with monitor_groups. I got this strange message when I re-run a pipeline without code changes.

```
      ~ monitor_groups          = [
          - "132963000030920001",
            "132963000030907001",
          + "132963000030920001",
        ]
```

**Comment by jim-billy-zoho** [comment]
@e-bits Thank you for raising this issue. Please use the latest version and let us know your feedback.

**Comment by e-bits** [comment]
Hi @jim-billy-zoho thanks for your fix. We already tested the latest provider Version `1.0.51` and it is working as expected. No further changes getting displayed if there are no changes regarding `monitor_groups`
