### ISSUE TITLE
Feature request: add ability to add tag_ids to monitors resources

### ISSUE THREAD

**Issue by azhurbilo** [site24x7/terraform-provider-site24x7#18]
add ability to add **tag** field to all types of monitor resources
- https://github.com/site24x7/terraform-provider-site24x7/blob/main/docs/resources/website_monitor.md
- https://github.com/site24x7/terraform-provider-site24x7/blob/main/docs/resources/rest_api_monitor.md
- https://github.com/site24x7/terraform-provider-site24x7/blob/main/docs/resources/ssl_monitor.md

https://www.site24x7.com/help/api/#monitor-parameters
**tag_ids**

**Comment by site24x7** [comment]
Tag association to resources is available in 0.0.1-beta.4
