### ISSUE TITLE
Feature request: add notification-profile resource support

### ISSUE THREAD

**Issue by azhurbilo** [site24x7/terraform-provider-site24x7#19]
add notification-profile resource support
https://www.site24x7.com/help/api/#notification-profiles

or if it's hard to implement, add terraform "data-source" support to have ability import id from manually created profile

**Comment by site24x7** [comment]
Notification Profile resource supported - 0.0.1-beta.8

Please refer the example - https://github.com/site24x7/terraform-provider-site24x7/blob/main/examples/notification_profile_us.tf

**Comment by terjavec** [comment]
Hi, seems strange that parameters:
- alert_configuration
- notification_delay_configuration
- persistent_alert_configuration
- escalation_levels

are just duplicated. Think in a normal use case this difficult us the workflow as if we need no add an "x" number of let's say alert_configuration per site24x7_notification_profile resource we cannot iterate over a list.

Is there any roadmap to change the parameter type to maybe list(object) so then if need to pass multiple (but not a fixed number can be done.


If I'm wrong please let me know if have some workaround!
