### ISSUE TITLE
Unexpected Block issue Version 1.0.66

### ISSUE THREAD

**Issue by markkellypayroc** [site24x7/terraform-provider-site24x7#215]
Hi, I am seeing this unexpected block for the read_time_out 

// (Optional) Triggers alert when not receiving the website entire HTTP response within 30 seconds.
  read_time_out {
    severity = 3
    value =true
  }

this is for a website threshold profile - any ideas welcome

![image](https://github.com/site24x7/terraform-provider-site24x7/assets/89018369/c5cc716e-924f-4ede-9e8a-a5eadb3f55ce)

**Comment by jim-billy-zoho** [comment]
@markkellypayroc Thank you for your patience. We have rectified the documentation error. "=" is missing after the "read_time_out" attribute.

```
read_time_out = {
    severity = 3
    value =true
  }
```

Please refer - https://registry.terraform.io/providers/site24x7/site24x7/latest/docs/resources/threshold_profile
