### ISSUE TITLE
Feature request: add ability to add third_party_services to monitors resources

### ISSUE THREAD

**Issue by azhurbilo** [site24x7/terraform-provider-site24x7#22]
add ability to add third_party_services to monitors resources

support for all types of monitor resources

https://github.com/site24x7/terraform-provider-site24x7/blob/main/docs/resources/website_monitor.md
https://github.com/site24x7/terraform-provider-site24x7/blob/main/docs/resources/rest_api_monitor.md
https://github.com/site24x7/terraform-provider-site24x7/blob/main/docs/resources/ssl_monitor.md

https://www.site24x7.com/help/api/#create-monitor

**Comment by site24x7** [comment]
v0.0.1-beta.6 contains changes for configuring third party services to resources.

// (Optional) List of Third Party Service IDs to be associated to the monitor.
  third_party_service_ids = [
    "4567"
  ]

Refer the following example https://github.com/site24x7/terraform-provider-site24x7/blob/main/examples/website_monitor_us.tf
