### ISSUE TITLE
Cannot set monitor group tags

### ISSUE THREAD

**Issue by rtiinus-rr** [site24x7/terraform-provider-site24x7#248]
I can set tags for site24x7_website_monitor, but site24x7_monitor_group does not support it.

**Comment by jim-billy-zoho** [comment]
@rtiinus-rr Setting a monitor group for site24x7_website_monitor using the below configuration seems to work. Can you please give us more inputs on this issue and share the terminal output with debugging enabled using the command "export TF_LOG=TRACE"

`
resource "site24x7_website_monitor" "website_monitor_example" {
  display_name = "Example Monitor - Terraform"
  website = "https://www.example.com"
  monitor_groups = [ "12345000033224228" ]
}
`
