### ISSUE TITLE
Missing few values in Terraform config of Monitor Groups

### ISSUE THREAD

**Issue by kalyangitnew** [site24x7/terraform-provider-site24x7#266]
Hello,

When I do GET for monitor_groups in site24x7 it got json with user id values, notification profile id and health profile id ,...but same when I tried to create new monitor groups through Terraform why those values not mentioned in provder documentation to use and I see if I use also still it not accepting...Do we have any issue or any other way...and one more thing why Terraform import not supporting for monitor group. It will support or am I right it will not if that's the case of importing instead of recreating.

**Comment by jim-billy-zoho** [comment]
@kalyangitnew Thank you for raising this issue. We have fixed it in the latest version.

**Comment by kalyangitnew** [comment]
Can you give me the version you are talking about i didn't see any new version

**Comment by kalyangitnew** [comment]
One more thing in my issue how the import for pagerduty integration, slack integration, user groups and monitor groups not working.. it would be happy if we have feature I feel that I include in my issue

**Comment by kalyangitnew** [comment]
You want me to open new issue and I feel very happy all the resources which were allows importing...I see oauth providers webtoekn and few authentications are not by Terraform ?

**Comment by jim-billy-zoho** [comment]
> Can you give me the version you are talking about i didn't see any new version

Please refer - https://registry.terraform.io/providers/site24x7/site24x7/latest

**Comment by jim-billy-zoho** [comment]
> One more thing in my issue how the import for pagerduty integration, slack integration, user groups and monitor groups not working.. it would be happy if we have feature I feel that I include in my issue

Imports should work in the latest version. Please let us know if you face any issue.

**Comment by kalyangitnew** [comment]
> > One more thing in my issue how the import for pagerduty integration, slack integration, user groups and monitor groups not working.. it would be happy if we have feature I feel that I include in my issue
> 
> Imports should work in the latest version. Please let us know if you face any issue.

Ok

**Comment by kalyangitnew** [comment]
> > > One more thing in my issue how the import for pagerduty integration, slack integration, user groups and monitor groups not working.. it would be happy if we have feature I feel that I include in my issue
> > 
> > Imports should work in the latest version. Please let us know if you face any issue.
> 
It will be some what happy if we have all documentation how to use import in provider documentation..and want to check import works for all I raised above we need to look(pagerduty integration, slack integration, user groups and monitor groups)
