### ISSUE TITLE
Upgrade to 1.0.85 - Failure

### ISSUE THREAD

**Issue by bryanmcgrath-payroc** [site24x7/terraform-provider-site24x7#270]
Hey Support,

We've upgraded from 1.0.5 > 1.0.6 previously.
We're upgrading from 1.0.6 > 1.0.85 to utilize the new CRON module functionality.
We're seeing an odd response in our Scalr Run for our Terraform Provider for Site24x7 after the upgrade:
########################################################################################
Stack trace from the terraform-provider-site24x7_v1.0.85 plugin:
panic: interface conversion: interface {} is nil, not float64
goroutine 3057 [running]:
github.com/site24x7/terraform-provider-site24x7/site24x7.setCronResourceData(0xc0007609a0, 0xc000a64000)
	github.com/site24x7/terraform-provider-site24x7/site24x7/threshold_profile.go:568 +0x352
github.com/site24x7/terraform-provider-site24x7/site24x7.updateThresholdProfileResourceData(0xc0007609a0, 0xc000a64000)
	github.com/site24x7/terraform-provider-site24x7/site24x7/threshold_profile.go:500 +0x1b3
github.com/site24x7/terraform-provider-site24x7/site24x7.thresholdProfileRead(0xc0007609a0, 0xee95c0, 0xc000144040, 0xc0007609a0, 0x0)
	github.com/site24x7/terraform-provider-site24x7/site24x7/threshold_profile.go:417 +0x105
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000125680, 0xc0003a6960, 0xee95c0, 0xc000144040, 0xc0006e2
778, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/resource.go:455 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000182120, 0x10655f0, 0xc000b83f20, 0xc0003a6870
, 0xc000182120, 0xc000b83f20, 0xc0000d0a50)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0xec1840, 0xc000182120, 0x10655f0, 0xc000b83f20, 0xc000d1ac
00, 0x0, 0x10655f0, 0xc000b83f20, 0xc000146000, 0x298)
	github.com/hashicorp/terraform-plugin-sdk@v1.1.1/internal/tfplugin5/tfplugin5.pb.go:3153 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003902c0, 0x106de38, 0xc000581380, 0xc000a67f00, 0xc00023adb0, 0x15533b0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc0003902c0, 0x106de38, 0xc000581380, 0xc000a67f00, 0x0)

**Error: The terraform-provider-site24x7_v1.0.85 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.**

########################################################################################

Can you kindly assist us with pushing this upgrade across.

Thanks

**Comment by bryanmcgrath-payroc** [comment]
Can someone assist us with this one?

**Comment by jim-billy-zoho** [comment]
> Hey Support,
> 
> Can someone take a look at this?

@bryanmcgrath-payroc Can you please use the latest version of the provider 1.0.90 for fixing this issue. https://registry.terraform.io/providers/site24x7/site24x7/latest
