### ISSUE TITLE
[site24x7_amazon_monitor] Attributes are documented incorrectly

### ISSUE THREAD

**Issue by dhoppe** [site24x7/terraform-provider-site24x7#305]
Without the attribute `aws_discover_services` the Site24x7 Amazon Monitor cannot be created and fails with an unrelated error message.

```
╷
│ Error: External ID has been expired, kindly refresh the page and try again
│
│   with module.site24x7_amazon_monitor.site24x7_amazon_monitor.this,
│   on .terraform/modules/site24x7_amazon_monitor/main.tf line 11, in resource "site24x7_amazon_monitor" "this":
│   11: resource "site24x7_amazon_monitor" "this" {
│
╵
```

I already create a pull request to fix the documentation. https://github.com/site24x7/terraform-provider-site24x7/pull/304

**Comment by VinothDarwin-ZC** [comment]
We have updated the Amazon Monitor documentation to make the discovery service field mandatory.

Please feel free to use Terraform with our product and share your feedback.
Thanks, 
Vinoth.
