### ISSUE TITLE
[site24x7_user_group] Determining the user ID

### ISSUE THREAD

**Issue by dhoppe** [site24x7/terraform-provider-site24x7#307]
While the Site24x7 resource `site24x7_amazon_monitor` offers the possibility to define a user group based on the ID or the name, in the case of the resource `site24x7_user_group` the user must be defined based on the ID. 

However, there is no data source to determine the ID of a user. 

I have the feeling there is a chicken / egg situation here anyway. It somehow feels wrong to create the user first and then the group. 

It would make much more sense to create the groups first and explicitly define a list of groups based on the names when creating the users. Unfortunately the attribute `users` is mandatory.

**Comment by VinothDarwin-ZC** [comment]
We have released the User Data Source feature in Plugin version v1.0.93. Therefore, we are closing this issue now.

Please feel free to use Terraform with our product and share your feedback.
Thanks,
Vinoth K.
