### ISSUE TITLE
Support "REST API Transaction"

### ISSUE THREAD

**Issue by wesleywh** [site24x7/terraform-provider-site24x7#31]
There is no resource that currently supports "REST API Transaction" monitors. The biggest thing that is needed here are the "transaction steps".

You currently have a "REST API" but not the transaction form.

**Comment by JasperPaul** [comment]
@wesleywh We will work on it soon. Its already in our list. Thanks for notifying.

**Comment by wesleywh** [comment]
Is there a public board that I can view that will give me an idea of how long it will take to implement this?

**Comment by JasperPaul** [comment]
@wesleywh We don't have a public board. However, we recently started a slack channel where we discuss our plans. If you're interested I can add you there. It's a common one where other customers who are willing to contribute are also part of the channel. We discuss our plans so that we don't collide with development efforts.

**Comment by vv185060** [comment]
Can i be added to the slack channel as well @JasperPaul please?

**Comment by mleonrsos** [comment]
Has this feature been added? I don't see anything for API transactions.

**Comment by e-bits** [comment]
We're also heavily using "REST API Transaction" monitors. Recently we switched to use Terraform to deploy our monitors and we would be happy to also migrate these monitors to Terraform.
@JasperPaul please add me to the Slack Channel as well. Thanks

**Comment by mleonrsos** [comment]
@JasperPaul Do we have any progress on this? Can you add me to the slack channel regarding this?

**Comment by chalitha1989** [comment]
@JasperPaul Did we make any progress? We are planning to move all our monitors to tf but this is a huge blocker for us. We shall be most grateful if you can provide us with a timeline for this feature.

**Comment by jim-billy-zoho** [comment]
@chalitha1989 @mleonrsos @wesleywh @e-bits @vv185060 Thank you for your patience. We have supported REST API Transaction resource. Please refer - https://registry.terraform.io/providers/site24x7/site24x7/latest/docs/resources/rest_api_transaction_monitor
