### ISSUE TITLE
Feature Request: Allow user management

### ISSUE THREAD

**Issue by graemedowner** [site24x7/terraform-provider-site24x7#32]
Allow the creation / deletion of users via terraform

**Comment by JasperPaul** [comment]
Thanks for notifying, Graeme. We'll take it up In our next sprint.

**Comment by mamoit** [comment]
@jim-billy do you know if this is the pipeline?

**Comment by JasperPaul** [comment]
Hey folks, Thanks for requesting here. Unfortunately, we haven't taken any new requests now. 

We will be revisiting it mid of Q1 2023. This is an important segment for us and this will stay open and is being tracked.

However, we'll still accept pull requests for new enhancements from community, review and add them. We encourage you guys to contribute to this initiative. 

-Jasper Paul
Site24x7 PM

**Comment by JasperPaul** [comment]
Just give how this will work. Even if a new user is added, the new user has to accept the invitation for him to be able to access the tool. Unless there is an SSO, in which case user onboarding can happen from the SSO provider itself.
