### ISSUE TITLE
Feature Request: Allow passing of Cookie:zaaid for MSP customers

### ISSUE THREAD

**Issue by vv185060** [site24x7/terraform-provider-site24x7#54]
Hello, It would be great to have the option to set the Site24x7 required header "Cookie: zaaid=xxxxxxxxx" as a parameter for different MSP users.

https://www.site24x7.com/help/api/#msp-api

**Comment by vv185060** [comment]
Thank you @jim-billy-zoho for the new release 1.0.11 today.

**Comment by jim-billy** [comment]
@vv185060 Thank you for raising this feature request. Please use the latest version and let us know your feedback.
