### ISSUE TITLE
Wrong data type (maybe on purpose?) for check_frequency, returns null with terraform import

### ISSUE THREAD

**Issue by vv185060** [site24x7/terraform-provider-site24x7#66]
Is there any reason why this is int and then a conversion is done later from int -> string as required by the Site24x7 API for this attribute?

https://github.com/site24x7/terraform-provider-site24x7/blob/065ca074f93915ca6988dc27ef9c06da65b22505/site24x7/monitors/website.go#L86

Atm, if you try importing an monitor, and specify only **id**, it will pull the data for the other attributes but for this specific one will return *null*

I'm wondering if i'm missing something if there is a explicit need to use int then convert it to string?

**Comment by vv185060** [comment]
Thank you @jim-billy

**Comment by jim-billy-zoho** [comment]
@vv185060 Thank you for raising the issue. Please use the latest version 1.0.9 for the fix.
