### ISSUE TITLE
Feature Request: Add GraphQL as a request content type to RestAPI Monitor

### ISSUE THREAD

**Issue by marksieczkowski** [site24x7/terraform-provider-site24x7#74]
The GraphQL as a request content type is supported in the API and UI for RestAPI monitors already.

**Comment by jim-billy-zoho** [comment]
@marksieczkowski Added GraphQL as a request content type to RestAPI Monitor. Please refer the example https://github.com/site24x7/terraform-provider-site24x7/blob/main/examples/rest_api_monitor_us.tf
