### ISSUE TITLE
Support for subgroups

### ISSUE THREAD

**Issue by niksoper** [site24x7/terraform-provider-site24x7#88]
I see there is support for subgroups CRUD in the API docs but not the terraform provider. Is this on the road map?

Thanks!

**Comment by jim-billy-zoho** [comment]
@niksoper Please use the latest version 1.0.27 to add subgroups via terraform. https://github.com/site24x7/terraform-provider-site24x7/blob/main/examples/subgroup_us.tf

**Comment by niksoper** [comment]
Thanks for this - I'll try to get round to testing this soon (also https://github.com/site24x7/terraform-provider-site24x7/issues/90).
