### ISSUE TITLE
Invalid data error on aws_monitor_site24x7

### ISSUE THREAD

**Issue by Tiago-SD** [site24x7/terraform-provider-site24x7#96]
Hi Team,

I've already created some configuration in site24x7 using terraform but when I'm trying to configure the monitoring to one AWS account, it returns:
```
Error: Invalid data.
│
│   with site24x7_amazon_monitor.aws_monitor_site24x7,
│   on main.tf line 19, in resource "site24x7_amazon_monitor" "aws_monitor_site24x7":
│   19: resource "site24x7_amazon_monitor" "aws_monitor_site24x7" {
```
I've tried to do it with IAM User and by assuming a role the same way I would do it on the Site24x7 console.

Code Sample:
```
resource "site24x7_amazon_monitor" "aws_monitor_site24x7" {
  // (Required) Display name for the monitor
  display_name = "aws_added_via_terraform"
  // (Required) AWS access key
  aws_access_key = var.aws_access_key
  // (Required) AWS secret key
  aws_secret_key = var.aws_secret_key
  // (Optional) AWS discover frequency
  aws_discovery_frequency = 5
  // (Optional) AWS services to discover. See https://www.site24x7.com/help/api/#aws_discover_services
  // for knowing service ID.
  aws_discover_services = ["3"]
}
```

I would like to request your help.

Many thanks,
Tiago Domingues

**Comment by jim-billy-zoho** [comment]
Hi Tiago,

Can you please share us the details requested for debugging via our support channel.

Thanks & Regards,
Jim Billy

**Comment by Tiago-SD** [comment]
Hello Team,

Quick question, is there any plan to release a new version with this enabled?

Cheers,
Tiago

**Comment by jim-billy-zoho** [comment]
@Tiago-SD Thank you for your patience. We have supported Amazon monitor. Please refer - https://registry.terraform.io/providers/site24x7/site24x7/latest/docs/resources/amazon_monitor
